### ISSUE TITLE
iFit chirp interface file

### ISSUE THREAD

**Issue by markamman** [dougbradbury/iFitJava#1]
Thanks for making this available. I have an old treadmill that I would like to control through the audio interface. Your wiki contains a link to a file that is no longer accessible. Would you happen to still have a copy of it that you could share?
Thanks!
Mark

**Comment by edwinchenloo** [comment]
https://web.archive.org/web/20100528011220/http://www.ifit.com/iFitLive/supportIfitChirpResources.do

**Comment by markamman** [comment]
Thanks!

**Comment by dougbradbury** [comment]
Thank you to you both!  I updated the wiki to point to the web archive.  I hope you can make it work!
